"""Simple runtime text translation helpers for UI/gameplay text."""

from typing import Any, Dict

SUPPORTED_LANGUAGES = ("fr", "en")

_TRANSLATIONS: Dict[str, Dict[str, str]] = {
    "fr": {
        "language.fr": "Francais",
        "language.en": "Anglais",
        "menu.settings_title": "PARAMETRES",
        "menu.apply": "APPLIQUER",
        "menu.back": "RETOUR",
        "menu.auth_title": "CONNEXION MULTIJOUEUR",
        "menu.player": "Joueur",
        "menu.password": "Mot de passe",
        "menu.connect": "CONNEXION",
        "menu.enter_password": "Entrez un mot de passe",
        "menu.server_ip": "IP Serveur",
        "menu.port": "Port",
        "menu.fps": "FPS",
        "menu.resolution": "Resolution",
        "menu.fullscreen": "Plein ecran",
        "menu.music_volume": "Volume musique",
        "menu.effects_volume": "Volume effets",
        "menu.map_zoom": "Zoom carte",
        "menu.language": "Langue",
        "menu.loading": "CHARGEMENT",
        "menu.on": "ON",
        "menu.off": "OFF",
        "menu.disconnected": "Deconnecte du serveur !",
        "menu.net_error": "Echec : {reason}",
        "phone.peek": "TELEPHONE  [UP]",
        "phone.brand": "DELIVERY RUSH",
        "phone.home_title": "Applications",
        "phone.mission_in_progress": "Mission en cours...",
        "phone.deliveries": "Livraisons",
        "phone.gps": "GPS",
        "phone.shop": "Boutique",
        "phone.garage": "Garage",
        "phone.wiki": "Wiki",
        "phone.mission_lab": "Wiki",
        "phone.stats": "Stats",
        "phone.top10": "Top 10",
        "phone.party": "Equipe",
        "phone.loading_data": "Chargement...",
        "phone.party_offline": "Disponible en multijoueur",
        "phone.party_create": "Creer",
        "phone.party_leave": "Quitter",
        "phone.party_join": "Rejoindre",
        "phone.party_you": "Leader: {leader}  Joueurs: {size}",
        "phone.party_challenge_live": "LIVE",
        "phone.party_challenge_done": "TERMINE",
        "phone.party_challenge_failed": "ECHEC",
        "phone.party_challenge_shared": "Livraisons partagees",
        "phone.party_leader_start_only": "Seul le leader peut lancer la mission de party",
        "phone.party_bonus_50": "BONUS PARTY +50%",
        "phone.equipped": "Equipe: {model} {color}",
        "phone.available": "Disponibles",
        "phone.none": "Aucune mission",
        "phone.active_tag": "EN COURS",
        "phone.status_pickup": "Allez au ramassage",
        "phone.status_dropoff": "Vers la livraison",
        "phone.cargo": "Cargo",
        "phone.no_requirement": "Aucun prerequis",
        "phone.risky": "RISQUE",
        "phone.chill": "CHILL",
        "phone.abandon": "Abandon",
        "phone.incompatible": "INCOMPATIBLE",
        "phone.legend_you": "Vous",
        "phone.legend_pickup": "Pickup",
        "phone.legend_dropoff": "Livraison",
        "phone.legend_available": "Dispo",
        "phone.legend_places": "Lieux (liste)",
        "phone.legend_scroll_hint": "Molette: pages",
        "phone.free": "GRATUIT",
        "phone.btn_equipped": "EQUIPE",
        "phone.btn_equip": "EQUIPER",
        "phone.btn_buy": "ACHETER",
        "phone.btn_select": "SELECTIONNER",
        "phone.hint_heavy": "Ideal: missions chaine et cargaison",
        "phone.hint_express": "Ideal: missions express",
        "phone.hint_standard": "Ideal: missions standard",
        "phone.lab_formula_title": "Calcul des gains",
        "phone.lab_formula_gen": "Base mission = aleatoire(type) x distance x facteur vehicule.",
        "phone.lab_formula_risky": "Risque: +24% recompense, -14% temps limite.",
        "phone.lab_formula_finish": "A la fin: multiplicateur final borne entre x0.45 et x1.85.",
        "phone.lab_formula_mods": "Modifs: rapidite, collisions, style (drift), multi-etapes.",
        "phone.lab_money_title": "Combien on peut gagner",
        "phone.lab_money_calc": "Gain final = reward mission x multiplicateur de fin.",
        "phone.lab_current_range": "Missions visibles: {low}$ -> {high}$",
        "phone.lab_vehicle_title": "Impact du vehicule",
        "phone.lab_vehicle_profile": "Actuel: {model} ({vclass}) | Vmax {speed} | Cap {capacity}kg.",
        "phone.lab_vehicle_weights": "Poids de generation -> Standard {standard}, Express {express}, Chaine {chain}.",
        "phone.lab_vehicle_reward_factor": "Facteur de recompense vehicule: x{factor}.",
        "phone.lab_vehicle_bias": "Ton vehicule tire la generation vers {high} et freine {low}.",
        "phone.lab_vehicle_unlocks": "Tier {tier}: types debloques {unlocked}.",
        "phone.lab_cargo_title": "Cargaisons par type",
        "phone.lab_scroll_hint": "Molette / Haut-Bas: defiler",
        "phone.stats.money": "Argent",
        "phone.stats.deliveries": "Livraisons",
        "phone.stats.failed": "Echouees",
        "phone.stats.vehicles": "Vehicules",
        "phone.stats.distance": "Distance",
        "phone.stats.vehicle": "Vehicule: {model} {color}",
        "hud.players_online": "JOUEURS EN LIGNE",
        "hud.road": "ROUTE",
        "hud.party": "Equipe",
        "hud.cargo": "Cargo",
        "hud.class": "Classe",
        "hud.steps": "{count} ETAPES",
        "hud.robbery": "Risque braquage",
        "hud.robber_tag": "BRAQUEUR",
        "hud.popup.success": "MISSION REUSSIE",
        "hud.popup.failed": "MISSION ECHOUEE",
        "hud.popup.type": "Type",
        "hud.popup.object": "Objet",
        "hud.popup.gain": "Gain",
        "hud.popup.time": "Temps",
        "hud.popup.remaining": "Restant",
        "hud.popup.reason": "Cause",
        "hud.popup.total_time": "Temps total",
        "mission.class.compact": "Compacte",
        "mission.class.family": "Familiale",
        "mission.class.sport": "Sport",
        "mission.class.super": "Super",
        "mission.class.utility": "Utilitaire",
        "mission.class.truck": "Camion",
        "mission.type.standard": "Standard",
        "mission.type.express": "Express",
        "mission.type.chain": "Chaine",
        "mission.default_pickup": "Ramassage",
        "mission.default_dropoff": "Livraison",
        "mission.none_requirement": "Aucun prerequis",
        "mission.label_model": "Modele: {value}",
        "mission.label_class": "Classe: {value}",
        "mission.label_speed": "V>={value}",
        "mission.label_capacity": "Cap>={value}",
        "mission.in_progress": "Mission en cours",
        "mission.refused": "Mission refusee: {label}",
        "mission.vehicle_incompatible": "Vehicule incompatible ({label})",
        "mission.accepted": "Mission acceptee ! {objective}",
        "mission.not_found": "Mission non trouvee",
        "mission.server_refused": "Mission refusee par serveur: {reason}",
        "mission.abandoned": "Mission abandonnee",
        "mission.robbed": "Mission echouee ! Cargo vole.",
        "mission.failed_generic": "Mission echouee.",
        "mission.timeout": "Mission echouee ! Temps ecoule.",
        "mission.success": "Livraison reussie ! +{money}$ {rep}",
        "mission.pickup_done": "Colis recupere ! {objective}",
        "mission.step_done": "Etape validee ! {objective}",
        "mission.objective.pickup": "Ramassage ({step}/{total}): {name}",
        "mission.objective.dropoff": "Livraison ({step}/{total}): {name}",
        "mission.objective.step": "Etape ({step}/{total}): {name}",
        "mission.buy_owned": "Vehicule deja possede",
        "mission.buy_not_enough": "Pas assez d'argent",
        "mission.buy_success": "{model} {color} achete !",
        "cargo.colis": "colis",
        "cargo.alimentaire": "alimentaire",
        "cargo.documents": "documents",
        "cargo.medical": "medical",
        "cargo.vip": "vip",
        "cargo.urgent": "urgent",
        "cargo.materiel": "materiel",
        "cargo.lourd": "lourd",
        "cargo.industriel": "industriel",
        "mission.reason.failed": "echec",
        "mission.reason.timeout": "temps ecoule",
        "mission.reason.cancelled": "annulee",
        "mission.reason.abandoned": "abandonnee",
        "mission.reason.server_denied": "refusee serveur",
        "mission.reason.robbed": "cargo vole",
        "mission.reason.completed": "terminee",
    },
    "en": {
        "language.fr": "French",
        "language.en": "English",
        "menu.settings_title": "SETTINGS",
        "menu.apply": "APPLY",
        "menu.back": "BACK",
        "menu.auth_title": "MULTIPLAYER LOGIN",
        "menu.player": "Player",
        "menu.password": "Password",
        "menu.connect": "CONNECT",
        "menu.enter_password": "Enter a password",
        "menu.server_ip": "Server IP",
        "menu.port": "Port",
        "menu.fps": "FPS",
        "menu.resolution": "Resolution",
        "menu.fullscreen": "Fullscreen",
        "menu.music_volume": "Music volume",
        "menu.effects_volume": "Effects volume",
        "menu.map_zoom": "Map zoom",
        "menu.language": "Language",
        "menu.loading": "LOADING",
        "menu.on": "ON",
        "menu.off": "OFF",
        "menu.disconnected": "Disconnected from server!",
        "menu.net_error": "Failed: {reason}",
        "phone.peek": "PHONE  [UP]",
        "phone.brand": "DELIVERY RUSH",
        "phone.home_title": "Applications",
        "phone.mission_in_progress": "Mission running...",
        "phone.deliveries": "Deliveries",
        "phone.gps": "GPS",
        "phone.shop": "Shop",
        "phone.garage": "Garage",
        "phone.wiki": "Wiki",
        "phone.mission_lab": "Wiki",
        "phone.stats": "Stats",
        "phone.top10": "Top 10",
        "phone.party": "Party",
        "phone.loading_data": "Loading...",
        "phone.party_offline": "Available in multiplayer",
        "phone.party_create": "Create",
        "phone.party_leave": "Leave",
        "phone.party_join": "Join",
        "phone.party_you": "Leader: {leader}  Players: {size}",
        "phone.party_challenge_live": "LIVE",
        "phone.party_challenge_done": "DONE",
        "phone.party_challenge_failed": "FAILED",
        "phone.party_challenge_shared": "Shared deliveries",
        "phone.party_leader_start_only": "Only the leader can start a party mission",
        "phone.party_bonus_50": "PARTY BONUS +50%",
        "phone.equipped": "Equipped: {model} {color}",
        "phone.available": "Available",
        "phone.none": "No mission available",
        "phone.active_tag": "ACTIVE",
        "phone.status_pickup": "Go to pickup",
        "phone.status_dropoff": "Go to dropoff",
        "phone.cargo": "Cargo",
        "phone.no_requirement": "No requirement",
        "phone.risky": "RISKY",
        "phone.chill": "CHILL",
        "phone.abandon": "Abandon",
        "phone.incompatible": "INCOMPATIBLE",
        "phone.legend_you": "You",
        "phone.legend_pickup": "Pickup",
        "phone.legend_dropoff": "Dropoff",
        "phone.legend_available": "Available",
        "phone.legend_places": "Places (list)",
        "phone.legend_scroll_hint": "Wheel: pages",
        "phone.free": "FREE",
        "phone.btn_equipped": "EQUIPPED",
        "phone.btn_equip": "EQUIP",
        "phone.btn_buy": "BUY",
        "phone.btn_select": "SELECT",
        "phone.hint_heavy": "Best for chain cargo missions",
        "phone.hint_express": "Best for express missions",
        "phone.hint_standard": "Best for standard missions",
        "phone.lab_formula_title": "How rewards are calculated",
        "phone.lab_formula_gen": "Mission base = random(type) x distance x vehicle factor.",
        "phone.lab_formula_risky": "Risky missions: +24% reward, -14% time limit.",
        "phone.lab_formula_finish": "Final payout multiplier is clamped between x0.45 and x1.85.",
        "phone.lab_formula_mods": "Modifiers: speed, collisions, style (drift), multi-stop.",
        "phone.lab_money_title": "How much money you can earn",
        "phone.lab_money_calc": "Final payout = mission reward x completion multiplier.",
        "phone.lab_current_range": "Visible missions: {low}$ -> {high}$",
        "phone.lab_vehicle_title": "Vehicle impact",
        "phone.lab_vehicle_profile": "Current: {model} ({vclass}) | Top speed {speed} | Capacity {capacity}kg.",
        "phone.lab_vehicle_weights": "Generation weights -> Standard {standard}, Express {express}, Chain {chain}.",
        "phone.lab_vehicle_reward_factor": "Vehicle reward factor: x{factor}.",
        "phone.lab_vehicle_bias": "Your car favors {high} missions and suppresses {low} ones.",
        "phone.lab_vehicle_unlocks": "Tier {tier}: unlocked types {unlocked}.",
        "phone.lab_cargo_title": "Cargo by mission type",
        "phone.lab_scroll_hint": "Wheel / Up-Down: scroll",
        "phone.stats.money": "Money",
        "phone.stats.deliveries": "Deliveries",
        "phone.stats.failed": "Failed",
        "phone.stats.vehicles": "Vehicles",
        "phone.stats.distance": "Distance",
        "phone.stats.vehicle": "Vehicle: {model} {color}",
        "hud.players_online": "ONLINE PLAYERS",
        "hud.road": "ROAD",
        "hud.party": "Party",
        "hud.cargo": "Cargo",
        "hud.class": "Class",
        "hud.steps": "{count} STOPS",
        "hud.robbery": "Robbery risk",
        "hud.robber_tag": "ROBBER",
        "hud.popup.success": "MISSION SUCCESS",
        "hud.popup.failed": "MISSION FAILED",
        "hud.popup.type": "Type",
        "hud.popup.object": "Object",
        "hud.popup.gain": "Earned",
        "hud.popup.time": "Time",
        "hud.popup.remaining": "Left",
        "hud.popup.reason": "Reason",
        "hud.popup.total_time": "Total time",
        "mission.class.compact": "Compact",
        "mission.class.family": "Family",
        "mission.class.sport": "Sport",
        "mission.class.super": "Super",
        "mission.class.utility": "Utility",
        "mission.class.truck": "Truck",
        "mission.type.standard": "Standard",
        "mission.type.express": "Express",
        "mission.type.chain": "Chain",
        "mission.default_pickup": "Pickup",
        "mission.default_dropoff": "Dropoff",
        "mission.none_requirement": "No requirement",
        "mission.label_model": "Model: {value}",
        "mission.label_class": "Class: {value}",
        "mission.label_speed": "S>={value}",
        "mission.label_capacity": "Cap>={value}",
        "mission.in_progress": "Mission already active",
        "mission.refused": "Mission denied: {label}",
        "mission.vehicle_incompatible": "Incompatible vehicle ({label})",
        "mission.accepted": "Mission accepted! {objective}",
        "mission.not_found": "Mission not found",
        "mission.server_refused": "Mission denied by server: {reason}",
        "mission.abandoned": "Mission abandoned",
        "mission.robbed": "Mission failed! Cargo was stolen.",
        "mission.failed_generic": "Mission failed.",
        "mission.timeout": "Mission failed! Time is up.",
        "mission.success": "Delivery completed! +{money}$ {rep}",
        "mission.pickup_done": "Cargo picked up! {objective}",
        "mission.step_done": "Stop reached! {objective}",
        "mission.objective.pickup": "Pickup ({step}/{total}): {name}",
        "mission.objective.dropoff": "Dropoff ({step}/{total}): {name}",
        "mission.objective.step": "Stop ({step}/{total}): {name}",
        "mission.buy_owned": "Vehicle already owned",
        "mission.buy_not_enough": "Not enough money",
        "mission.buy_success": "{model} {color} purchased!",
        "cargo.colis": "package",
        "cargo.alimentaire": "food",
        "cargo.documents": "documents",
        "cargo.medical": "medical",
        "cargo.vip": "vip",
        "cargo.urgent": "urgent",
        "cargo.materiel": "equipment",
        "cargo.lourd": "heavy",
        "cargo.industriel": "industrial",
        "mission.reason.failed": "failed",
        "mission.reason.timeout": "time up",
        "mission.reason.cancelled": "cancelled",
        "mission.reason.abandoned": "abandoned",
        "mission.reason.server_denied": "server denied",
        "mission.reason.robbed": "cargo stolen",
        "mission.reason.completed": "completed",
    },
}


def normalize_language(value: Any) -> str:
    key = str(value or "fr").strip().lower()
    return key if key in SUPPORTED_LANGUAGES else "fr"


def tr(language: Any, key: str, **kwargs: Any) -> str:
    lang = normalize_language(language)
    text = _TRANSLATIONS.get(lang, {}).get(key)
    if text is None:
        text = _TRANSLATIONS["fr"].get(key, key)
    if kwargs:
        try:
            return text.format(**kwargs)
        except Exception:
            return text
    return text
